### ISSUE TITLE
InfluxDB Authorization error

### ISSUE THREAD

**Issue by Veids** [qlyoung/lagopus#5]
As I can see previously in deployment InfluxDB had 1.x version and there were no problem with authentication, but since 2.x release authentication is mandatory. So I guess that's why I get spam off 401 error messages in the log:
```
[2021-09-16 11:31:48,889] WARNING in lagopus: Requesting since: None
[2021-09-16 11:31:48,892] ERROR in lagopus: InfluxDB error: 401: {"code":"unauthorized","message":"Unauthorized"}
```
Also, there's no any graph data in the web panel

**Comment by qlyoung** [comment]
Thank you for reporting and fixing this! Sorry it took me so long to reply, I have github notifications turned off otherwise I get way too many of them.
